branch-defaults:
  master:
    environment: shop02-dev
  phase4a:
    environment: shop02-dev
global:
  application_name: shop02
  default_ec2_keyname: aws-eb
  default_platform: 64bit Amazon Linux 2014.09 v1.1.0 running Node.js
  default_region: ap-southeast-1
  profile: eb-cli
  sc: git
