branch-defaults:
  master:
    environment: shop02-dev
global:
  application_name: shop02
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: ap-southeast-1
  profile: eb-cli
  sc: git
